PACKAGE_NAME=clevofan
PACKAGE_VERSION=1.1+diamon1

DEST_MODULE_LOCATION[0]="/kernel/lib/"
BUILT_MODULE_NAME[0]="clevofan"
BUILT_MODULE_LOCATION[0]="."

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean KDIR=/lib/modules/${kernelver}/build"
AUTOINSTALL="yes"
